## Linear regression Multiple variables

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [11]:
df=pd.read_csv('./resources/hiring.csv')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
#preprocessing
df.experience=df.experience.fillna('zero')
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
#new_learing
from word2number import w2n
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [26]:
#preprocessing
median_score=math.floor(df['test_score(out of 10)'].median())
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_score)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [27]:
lr=linear_model.LinearRegression()
lr.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])
print("Regression coefficients are",lr.coef_)
print("Regression intercept is",lr.intercept_)

Regression coefficients are [2812.95487627 1845.70596798 2205.24017467]
Regression intercept is 17737.263464337688

In [29]:
lr.predict([[2,9,6]])

C:\Users\farah\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53205.96797671])

In [31]:
lr.predict([[12,10,10]])

C:\Users\farah\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([92002.18340611])